name: Build and deploy accml_lib docs

on:
  push:
    branches: [ main ]   # build on pushes to main (adjust as needed)
  pull_request:
    branches: [ main ]

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          submodules: true

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.11'  # choose your supported version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python3 -m pip install -e ./[bluesky-epics,docs,pyat-simulator]

      - name: Build docs
        working-directory: docs
        run: |
          find . -type d
          cd docs/
          python3 -m sphinx.ext.apidoc -o src/ ../src/accml_lib/  || echo  "failed to create auto/API docs!"
          python3 -m sphinx.cmd.build --conf-dir ./  ./ _build/html/
          cd ..

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/_build/html
          # optional: cname: docs.example.com
